server:
  port: 8080



eureka:
  client:
    service-url:
      defaultZone: http://peer1:1010/eureka/,http://peer2:1011/eureka/,http://peer3:1012/eureka/
  instance:
    prefer-ip-address: true # 以自己的ip 作为注册访问地址
    instance-id: zuul-server:8080 #在仪表盘显示自己的服务标识



spring:
  application:
    name: zuul-8080

zuul:
  prefix: "/server"    # 统一的请求前缀
  ignored-services: "*"
  routes:
    order-server: "/systemOrder/**"
    user-server: "/systemUser/**"